[package]
name = "echo-rs"
version = "0.1.0"
edition = "2021"
authors = ["Olivier Ory <mail@olivierory.eu>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
trycmd = "0.14.19"
